apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-scheduler
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BROKERS: kafka:9092
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  PROMETHEUS_URL: "http://prometheus:9090"
