apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-scheduler-ingress
  namespace: task-scheduler
spec:
  ingressClassName: nginx
  rules:
    # UI: everything at dst.jougan.live -> UI
    - host: dst.jougan.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 3000

    # Backend: everything at api-dst.jougan.live -> backend
    - host: api-dst.jougan.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
