apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: task-scheduler
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASS: YWRtaW4=
  DB_NAME: dGFza3NfZGI=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_DB: dGFza3NfZGI=