apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-scheduler
data:
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: "{{ .Values.redis.port }}"
  KAFKA_BROKERS: "{{ .Values.kafka.brokers }}"
  ELASTICSEARCH_URL: "{{ .Values.elasticsearch.url }}"
  PROMETHEUS_URL: "{{ .Values.prometheus.url }}"