apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: task-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: {{ .Values.image.kibana }}
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "{{ .Values.elasticsearch.url }}"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: task-scheduler
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
---