apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: task-scheduler
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc }}
  DB_PASS: {{ .Values.db.password | b64enc }}
  DB_NAME: {{ .Values.db.name | b64enc }}
  POSTGRES_USER: {{ .Values.db.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc }}
  POSTGRES_DB: {{ .Values.db.name | b64enc }}